### ISSUE TITLE
8.3 CornerIndicators error

### ISSUE THREAD

**Issue by snowanimal** [stealwater/CompactRaid-Continued#10]
I got several corner indicator errors in-game.
Compactraid can't display Atonement, renew on the frame...

Here is the code"

----------------------
...dOns\CompactRaid\Modules\CornerIndicators\Visual.lua:248: attempt to index a nil value
[string "@CompactRaid\Modules\CornerIndicators\Visual.lua"]:248: in function `func'
[string "@CompactRaid\Includes\LibAddonManager-1.27.nil.lua"]:591: in function `CallModule'
[string "@CompactRaid\Modules\Manager.lua"]:68: in function `func'
[string "@CompactRaid\Includes\LibAddonManager-1.27.nil.lua"]:579: in function `EnumModules'
[string "@CompactRaid\Modules\Manager.lua"]:73: in function `func'
[string "@CompactRaid\Includes\LibAddonManager-1.27.nil.lua"]:495: in function `BroadcastEvent'
[string "@CompactRaid\UnitFrames\UnitButton.lua"]:109: in function <CompactRaid\UnitFrames\UnitButton.lua:107>
[string "@CompactRaid\UnitFrames\UnitButton.lua"]:337: in function <CompactRaid\UnitFrames\UnitButton.lua:308>
[string "@CompactRaid\UnitFrames\UnitButton.lua"]:1031: in function <CompactRaid\UnitFrames\UnitButton.lua:1025>
----------------------
CompactRaid\Modules\CornerIndicators\Core.lua:53: attempt to index local 'visual' (a nil value)
[string "@CompactRaid\Modules\CornerIndicators\Core.lua"]:53: in function `func'
[string "@CompactRaid\Includes\LibAddonManager-1.27.nil.lua"]:591: in function `CallModule'
[string "@CompactRaid\Modules\Manager.lua"]:68: in function `func'
[string "@CompactRaid\Includes\LibAddonManager-1.27.nil.lua"]:579: in function `EnumModules'
[string "@CompactRaid\Modules\Manager.lua"]:73: in function `func'
[string "@CompactRaid\Includes\LibAddonManager-1.27.nil.lua"]:495: in function `BroadcastEvent'
[string "@CompactRaid\UnitFrames\UnitButton.lua"]:109: in function <CompactRaid\UnitFrames\UnitButton.lua:107>
[string "@CompactRaid\UnitFrames\UnitButton.lua"]:574: in function <CompactRaid\UnitFrames\UnitButton.lua:570>
[string "@CompactRaid\UnitFrames\UnitButton.lua"]:878: in function <CompactRaid\UnitFrames\UnitButton.lua:857>
[string "@CompactRaid\UnitFrames\UnitButton.lua"]:985: in function <CompactRaid\UnitFrames\UnitButton.lua:968>
[string "@CompactRaid\UnitFrames\UnitButton.lua"]:995: in function <CompactRaid\UnitFrames\UnitButton.lua:992>
------------------------
CompactRaid\Modules\CornerIndicators\Core.lua:68: attempt to index local 'visual' (a nil value)
[string "@CompactRaid\Modules\CornerIndicators\Core.lua"]:68: in function `func'
[string "@CompactRaid\Includes\LibAddonManager-1.27.nil.lua"]:591: in function `CallModule'
[string "@CompactRaid\Modules\Manager.lua"]:68: in function `func'
[string "@CompactRaid\Includes\LibAddonManager-1.27.nil.lua"]:579: in function `EnumModules'
[string "@CompactRaid\Modules\Manager.lua"]:73: in function `func'
[string "@CompactRaid\Includes\LibAddonManager-1.27.nil.lua"]:495: in function `BroadcastEvent'
[string "@CompactRaid\UnitFrames\UnitButton.lua"]:109: in function <CompactRaid\UnitFrames\UnitButton.lua:107>
[string "@CompactRaid\UnitFrames\UnitButton.lua"]:831: in function <CompactRaid\UnitFrames\UnitButton.lua:819>
[string "@CompactRaid\UnitFrames\UnitButton.lua"]:980: in function <CompactRaid\UnitFrames\UnitButton.lua:968>
[string "@CompactRaid\UnitFrames\UnitButton.lua"]:995: in function <CompactRaid\UnitFrames\UnitButton.lua:992>

**Comment by stealwater** [comment]
Would you mind providing your CompactRaid setting profile? I cannot see any problem in these error logs. 

Please copy & paste the content of the following file. 
`World of Warcraft\_retail_\WTF\Account\<Your Account>\SavedVariables\CompactRaid.lua `

P.S. You can erase your character's information if you have privacy concern.

**Comment by snowanimal** [comment]
OK! please see the code below.
Because I play WOW at the ZhTW server, therefore spells are Chinese words.
I don't know do these cause errors.

-------------------------------------------------
CompactRaidDB = {
	["keepgroupstogether"] = 1,
	["showtooltip"] = 1,
	["healthColor"] = "0.0,1.0,0.0",
	["modules"] = {
		["Artwork"] = {
			["statusbar"] = "Interface\\AddOns\\WorldQuestTracker\\media\\bar_serenity",
			["background"] = "Interface\\DialogFrame\\UI-DialogBox-Background",
			["border"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["font"] = "Fonts\\bKAI00M.ttf",
		},
		["RaidDebuff"] = {
			["scale"] = 130,
			["userLevels"] = {
			},
			["selTier"] = 8,
			["customDebuffs"] = {
			},
			["xoffset"] = 0,
			["selBoss"] = 2352,
			["selInstance"] = 1179,
			["yoffset"] = 0,
		},
	},
	["lock"] = 1,
	["powerColor"] = "0.0,0.0,1.0",
	["groupSwapNoNotify"] = 1,
	["showToolboxes"] = 1,
	["outrangeAlpha"] = 40,
	["showRoleIcon"] = 1,
	["nameWidthLimit"] = 100,
	["showDispels"] = 1,
	["unitBkColor"] = "0.0,0.0,0.0",
	["showbarbkgnd"] = 1,
	["height"] = 44,
	["showPrivIcons"] = 1,
	["nameYOffset"] = 4,
	["tooltipPosition"] = 1,
	["scale"] = 100,
	["showBuffs"] = 1,
	["spacing"] = 1,
	["width"] = 82,
	["showRaidIcon"] = 1,
	["containerBorderSize"] = 1,
	["showVehicleHealthBar"] = 1,
	["version"] = 5.1,
	["nameHeight"] = 10,
	["nameFontOutline"] = 1,
	["raidFilter"] = "CLASS",
	["profiles"] = {
		["ID - Server"] = {
			["modules"] = {
				["ClickSets"] = {
					["talent3"] = {
						["1"] = "action:target",
						["ctrl-2"] = "buildin:真言術：盾",
						["alt-ctrl-1"] = "buildin:守護聖靈",
						["2"] = "action:togglemenu",
						["ctrl-1"] = "buildin:恢復",
						["alt-2"] = "buildin:癒合禱言",
						["shift-2"] = "buildin:驅淨術",
						["shift-1"] = "buildin:快速治療",
						["alt-1"] = "buildin:治療術",
					},
					["talent1"] = {
						["1"] = "action:target",
						["ctrl-2"] = "buildin:真言術：盾",
						["alt-ctrl-1"] = "buildin:守護聖靈",
						["2"] = "action:togglemenu",
						["ctrl-1"] = "buildin:恢復",
						["alt-2"] = "buildin:癒合禱言",
						["shift-2"] = "buildin:驅淨術",
						["shift-1"] = "buildin:快速治療",
						["alt-1"] = "buildin:治療術",
						["3"] = "buildin:驅淨術",
					},
				},
				["CornerIndicators"] = {
					["talent3"] = {
						["TOPLEFT"] = "[selfcast]#1#[aura]#恢復#[style]#2#",
						["TOPRIGHT"] = "[selfcast]#1#[scale]#120#[ignoreVehicle]#1#[aura]#真言術：盾#[b1]#0.0#[b2]#0.0#[b3]#0.0#[g1]#1.0#[g3]#0.0#[g2]#1.0#[r3]#1.0#[r1]#0.0#[r2]#1.0#",
						["BOTTOMLEFT"] = "[ignoreVehicle]#1#[aura]#癒合禱言#",
					},
					["talent1"] = {
						["TOPLEFT"] = "[selfcast]#1#[scale]#150#[aura]#真言術:壁#[b1]#0.0#[b2]#0.0#[b3]#0.0#[g1]#1.0#[g3]#0.0#[g2]#1.0#[r3]#1.0#[threshold3]#3#[style]#2#[r1]#0.0#[r2]#1.0#",
						["TOPRIGHT"] = "[selfcast]#1#[scale]#150#[ignoreVehicle]#1#[aura]#真言術：盾#[b1]#0.0#[b2]#0.0#[b3]#0.0#[g1]#1.0#[g3]#0.0#[g2]#1.0#[r3]#1.0#[r1]#0.0#[r2]#1.0#",
						["RIGHT"] = "[selfcast]#1#[scale]#150#[ignoreVehicle]#1#[aura]#痛苦鎮壓#[b1]#0.0#[b2]#0.0#[b3]#0.0#[g1]#1.0#[g3]#0.0#[g2]#1.0#[r3]#1.0#[style]#0#[r1]#0.0#[r2]#1.0#",
						["BOTTOMRIGHT"] = "[selfcast]#1#[scale]#150#[aura]#贖罪#[b1]#0.0#[b2]#0.0#[b3]#0.0#[g1]#1.0#[g3]#0.0#[g2]#1.0#[r3]#1.0#[style]#2#[r1]#0.0#[r2]#1.0#",
						["BOTTOMLEFT"] = "[selfcast]#1#[ignoreVehicle]#1#[aura]#贖罪#[b1]#0.0#[b2]#0.0#[b3]#0.0#[g1]#1.0#[g3]#0.0#[g2]#1.0#[r3]#1.0#[r1]#0.0#[r2]#1.0#",
						["LEFT"] = "[scale]#120#[ignoreVehicle]#1#[aura]#真言術：韌#[showlacks]#1#[b1]#0.0#[b2]#0.0#[b3]#0.0#[g1]#1.0#[g3]#0.0#[g2]#1.0#[r3]#1.0#[r1]#0.0#[r2]#1.0#",
					},
				},
			},
			["showPartyPets"] = 1,
			["version"] = 5.1,
			["showFriendlyNpc"] = 1,
		},
		["ID - Server"] = {
			["modules"] = {
				["CornerIndicators"] = {
					["talent1"] = {
						["TOPRIGHT"] = "[selfcast]#1#[aura]#野性痊癒#[style]#2#",
						["TOPLEFT"] = "[selfcast]#1#[aura]#回春術#[style]#2#",
						["BOTTOMLEFT"] = "[selfcast]#1#[aura]#生命之花#[style]#2#",
					},
				},
				["ClickSets"] = {
					["talent1"] = {
						["1"] = "action:target",
						["ctrl-1"] = "buildin:回春術",
						["ctrl-2"] = "buildin:生命之花",
						["shift-1"] = "buildin:癒合",
						["shift-2"] = "buildin:自然療癒",
						["alt-ctrl-2"] = "buildin:野性痊癒",
						["alt-2"] = "buildin:迅癒",
						["2"] = "action:togglemenu",
					},
				},
			},
			["version"] = 5.1,
			["showPartyPets"] = 1,
		},
	},
	["healthtextmode"] = 2,
	["showDirectionArrow"] = 1,
	["powerBarHeight"] = 7,
	["nameColor"] = "1.0,1.0,1.0",
	["nameXOffset"] = 0,
	["containerAlpha"] = 0,
	["invertColor"] = 1,
	["onlyDispellable"] = 1,
}

**Comment by stealwater** [comment]
This commit (https://github.com/stealwater/CompactRaid-Continued/commit/a8a1fcb21d8ceef445e6811c09cd31099f7fd6cb) should fixed this issue. 


Please test the v5.11, thanks.
