### ISSUE TITLE
Dragonflight (10.0.0) version upgrade

### ISSUE THREAD

**Issue by evalor** [stealwater/CompactRaid-Continued#25]
Is anyone interested in this?

**Comment by Zimxx1225** [comment]
YES!!!!!!!!!! I have tried all the current raidframs and they are either too complex or not complex enough. Compact Raidframes has always been the best middle ground.

So please update!

**Comment by evalor** [comment]
Yes, is best raidframs i have ever used. Now I'm reading the source code and trying to make it work continued. I use a few spare time to do it, it seems that some progress has been made, now some functions can work for me, and I will try to continue to improve it.

**Comment by evalor** [comment]
There is still a lua error. I will go to work soon, and I will continue later.

**Comment by ghost** [comment]
> There is still a lua error. I will go to work soon, and I will continue later.

Can't wait for my hero back!

**Comment by evalor** [comment]
This is an alpha fix for Dragonflight (10.0.0). There are still a lot of problems that have not been properly addressed.

Download: [v7.00](https://github.com/evalor/CompactRaid-Continued/releases/tag/v7.00)

**Comment by evalor** [comment]
> This is an alpha fix for Dragonflight (10.0.0). There are still a lot of problems that have not been properly addressed.
> 
> Download: [v7.00](https://github.com/evalor/CompactRaid-Continued/releases/tag/v7.00)

A large number of FrameXML-API have been removed due to the UI interface update, You may continue to receive lua error prompts or some functions are abnormal. Please do not use this version for important raids.

**Comment by evalor** [comment]
I tested this version in Mythic+ , and the function performance is basically good. Except for the RaidDebuff module, everything else should work normally.

**Comment by Utyfus** [comment]
> thank you so much for ressurect this best frame addon <3

**Comment by ghost** [comment]
Thank you for the update :)

**Comment by cklking78** [comment]
Thank you! 英雄登场！还正烦恼著是不是要转用cell就看到这个thread了

**Comment by evalor** [comment]
At present, almost all functions are working for me. Except that the UI of the interface is a little abnormal, which involves too many old APIs and UI Layout Frames, I am trying to continue to improve it.

**Comment by evalor** [comment]
The newly released version v7.1.0 fixes the Lua error of the setting interface, and adds RaidDebuff of the Sepulcher.

I have created a new repository and continue to complete the maintenance work in Dragonflight (10.0.0). Please go to the repository to download the latest code. If you encounter problems, please raise them in Issues so that I can repair them.

[CompactRaid](https://github.com/evalor/CompactRaid)
